# yazi keymap.toml
# プラグインキーバインド設定

[[manager.prepend_keymap]]
on = "s"
run = "plugin fzf"
desc = "Search files with fzf"

[[manager.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"
